#!/usr/bin/env python3
"""Embed the Bolo JavaScript into the firmware.

Reads  shared/lang/trashbot-lang.mjs   (served by the robot as /lang.mjs)
       shared/lang/web/bolo-ui.mjs      (served by the robot as /bolo-ui.mjs)
Writes firmware/lib/net/web_lang.h      (two raw-string constants, stored in flash)

Usage (repo root):
  python tools/embed_lang.py            regenerate the header
  python tools/embed_lang.py --check    exit 1 if the header is missing or stale (CI / release_check)
Python standard library only.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [
    ("WEB_LANG_MJS", ROOT / "shared" / "lang" / "trashbot-lang.mjs", "/lang.mjs"),
    ("WEB_BOLO_UI_MJS", ROOT / "shared" / "lang" / "web" / "bolo-ui.mjs", "/bolo-ui.mjs"),
]
DEFAULT_OUT = ROOT / "firmware" / "lib" / "net" / "web_lang.h"
DELIM = "TBJS"
MAX_BYTES = 200_000  # sanity limit per file (flash is 8 MB; this keeps the page fast on WiFi)


def render(sources=SOURCES) -> str:
    parts = [
        "// GENERATED by tools/embed_lang.py — do not edit by hand.",
        "// Source of truth: shared/lang/. Regenerate: python tools/embed_lang.py",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
    ]
    for name, path, route in sources:
        text = path.read_text(encoding="utf-8")
        if f"){DELIM}\"" in text:
            raise SystemExit(f"{path}: contains the raw-string delimiter ){DELIM}\" — change DELIM")
        size = len(text.encode("utf-8"))
        if size > MAX_BYTES:
            raise SystemExit(f"{path}: {size} bytes > {MAX_BYTES}")
        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
        parts += [
            f"// {route}  ←  {path.relative_to(ROOT).as_posix()}  ({size} bytes, sha256 {sha})",
            f'static const char {name}[] PROGMEM = R"{DELIM}({text}){DELIM}";',
            "",
        ]
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if the header is missing or out of date")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output header path")
    args = ap.parse_args(argv)
    text = render()
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current != text:
            print(f"{args.out} is out of date. Run: python tools/embed_lang.py", file=sys.stderr)
            return 1
        print("web_lang.h is up to date")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(text.encode('utf-8'))} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
